### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by killsky** [Baozisoftware/luci-app-koolproxy#1]
日志报错：
Sat Jul 20 04:00:10 2019 user.notice root: koolproxy restart service.
Sat Jul 20 04:00:10 2019 user.notice root: koolproxy has stopped.
Sat Jul 20 04:00:11 2019 user.notice root: koolproxy has started.
Sat Jul 20 04:00:11 2019 daemon.info koolproxy[20798]: koolproxy v3.8.4
Sat Jul 20 04:00:12 2019 daemon.err koolproxy[20798]: rule line=20032 not support ','
Sat Jul 20 04:00:12 2019 daemon.err koolproxy[20798]: rule line=21051 not support ','
Sat Jul 20 04:00:12 2019 daemon.err koolproxy[20798]: rule line=21717 not support ','
Sat Jul 20 04:00:12 2019 daemon.err koolproxy[20798]: rule line=25734 not support ','
Sat Jul 20 04:00:12 2019 daemon.err koolproxy[20798]: rule line=26753 not support ','
Sat Jul 20 04:00:12 2019 daemon.err koolproxy[20798]: rule line=27419 not support ','

全局模式
全部过滤
部分网站无法访问，或只能显示文字，没有图片和任何css，例如：https://sports.qq.com/f1/
QQ视频客户端没有广告视频，但是有声音。
视频模式
全部过滤
QQ视频客户端依然有广告，之前koolproxy可以过滤，美团订单无法下单。

**Comment by zxlhhyccc** [comment]
> 日志报错：
> Sat Jul 20 04:00:10 2019 user.notice root: koolproxy restart service.
> Sat Jul 20 04:00:10 2019 user.notice root: koolproxy has stopped.
> Sat Jul 20 04:00:11 2019 user.notice root: koolproxy has started.
> Sat Jul 20 04:00:11 2019 daemon.info koolproxy[20798]: koolproxy v3.8.4
> Sat Jul 20 04:00:12 2019 daemon.err koolproxy[20798]: rule line=20032 not support ','
> Sat Jul 20 04:00:12 2019 daemon.err koolproxy[20798]: rule line=21051 not support ','
> Sat Jul 20 04:00:12 2019 daemon.err koolproxy[20798]: rule line=21717 not support ','
> Sat Jul 20 04:00:12 2019 daemon.err koolproxy[20798]: rule line=25734 not support ','
> Sat Jul 20 04:00:12 2019 daemon.err koolproxy[20798]: rule line=26753 not support ','
> Sat Jul 20 04:00:12 2019 daemon.err koolproxy[20798]: rule line=27419 not support ','
> 
> 全局模式
> 全部过滤
> 部分网站无法访问，或只能显示文字，没有图片和任何css，例如：https://sports.qq.com/f1/
> QQ视频客户端没有广告视频，但是有声音。
> 视频模式
> 全部过滤
> QQ视频客户端依然有广告，之前koolproxy可以过滤，美团订单无法下单。

还有一个小问题：视频规则条数不显示。。。。

**Comment by Baozisoftware** [comment]
这个fork只是修改原版的一些UI上的内容,并打包了第三方的规则,没对规则进行任何处理,仅仅是打包,如果是规则引起的问题,请反馈给提供规则的repo,视频规则是加密的,取不到条数,故意去掉的,原版之所以有条数是因为koolshare提供了一个明文的规则信息,里面包含有视频规则的条数等等,现在它已经404了,所以也就无意义了.
