### ISSUE TITLE
Bug？或如何设置？

### ISSUE THREAD

**Issue by RealKiro** [Baozisoftware/luci-app-koolproxy#2]
经测试体验，开了该插件会对SSR Plus的科学上网有影响（不是偶然性事件），但电报telegram是正常的
![image](https://user-images.githubusercontent.com/33367701/62109195-57617780-b2de-11e9-8f90-f45e49701fe1.png)

**Comment by binge8** [comment]
我也遇到同样的问题，https://github.com/coolsnowwolf/lede用的这个源码编译的固件，luci-app-ssr-plus这个插件有个节点验证机制，当某个节点验证连不通google.com的时候，就会自动切换另一个节点。只要打开您的KP，就会验证失败，所以会导致无休止的切换节点中，但是实际上是可以打开google.com的，可以连通的。不知道是哪里冲突了导致验证机制失败。关了你的kp就一切正常。原版kp是没有冲突的，一切正常。

**Comment by RealKiro** [comment]
> 我也遇到同样的问题，[https://github.com/coolsnowwolf/lede用的这个源码编译的固件，luci-app-ssr-plus这个插件有个节点验证机制，当某个节点验证连不通google.com的时候，就会自动切换另一个节点。只要打开您的KP，就会验证失败，所以会导致无休止的切换节点中，但是实际上是可以打开google.com的，可以连通的。不知道是哪里冲突了导致验证机制失败。关了你的kp就一切正常。原版kp是没有冲突的，一切正常。](https://github.com/coolsnowwolf/lede%E7%94%A8%E7%9A%84%E8%BF%99%E4%B8%AA%E6%BA%90%E7%A0%81%E7%BC%96%E8%AF%91%E7%9A%84%E5%9B%BA%E4%BB%B6%EF%BC%8Cluci-app-ssr-plus%E8%BF%99%E4%B8%AA%E6%8F%92%E4%BB%B6%E6%9C%89%E4%B8%AA%E8%8A%82%E7%82%B9%E9%AA%8C%E8%AF%81%E6%9C%BA%E5%88%B6%EF%BC%8C%E5%BD%93%E6%9F%90%E4%B8%AA%E8%8A%82%E7%82%B9%E9%AA%8C%E8%AF%81%E8%BF%9E%E4%B8%8D%E9%80%9Agoogle.com%E7%9A%84%E6%97%B6%E5%80%99%EF%BC%8C%E5%B0%B1%E4%BC%9A%E8%87%AA%E5%8A%A8%E5%88%87%E6%8D%A2%E5%8F%A6%E4%B8%80%E4%B8%AA%E8%8A%82%E7%82%B9%E3%80%82%E5%8F%AA%E8%A6%81%E6%89%93%E5%BC%80%E6%82%A8%E7%9A%84KP%EF%BC%8C%E5%B0%B1%E4%BC%9A%E9%AA%8C%E8%AF%81%E5%A4%B1%E8%B4%A5%EF%BC%8C%E6%89%80%E4%BB%A5%E4%BC%9A%E5%AF%BC%E8%87%B4%E6%97%A0%E4%BC%91%E6%AD%A2%E7%9A%84%E5%88%87%E6%8D%A2%E8%8A%82%E7%82%B9%E4%B8%AD%EF%BC%8C%E4%BD%86%E6%98%AF%E5%AE%9E%E9%99%85%E4%B8%8A%E6%98%AF%E5%8F%AF%E4%BB%A5%E6%89%93%E5%BC%80google.com%E7%9A%84%EF%BC%8C%E5%8F%AF%E4%BB%A5%E8%BF%9E%E9%80%9A%E7%9A%84%E3%80%82%E4%B8%8D%E7%9F%A5%E9%81%93%E6%98%AF%E5%93%AA%E9%87%8C%E5%86%B2%E7%AA%81%E4%BA%86%E5%AF%BC%E8%87%B4%E9%AA%8C%E8%AF%81%E6%9C%BA%E5%88%B6%E5%A4%B1%E8%B4%A5%E3%80%82%E5%85%B3%E4%BA%86%E4%BD%A0%E7%9A%84kp%E5%B0%B1%E4%B8%80%E5%88%87%E6%AD%A3%E5%B8%B8%E3%80%82%E5%8E%9F%E7%89%88kp%E6%98%AF%E6%B2%A1%E6%9C%89%E5%86%B2%E7%AA%81%E7%9A%84%EF%BC%8C%E4%B8%80%E5%88%87%E6%AD%A3%E5%B8%B8%E3%80%82)

问问大屌，看他有什么建议

**Comment by Baozisoftware** [comment]
原版KP是什么意思?koolshare官方的那个吗?还是
https://github.com/openwrt-develop/luci-app-koolproxy
这个?我自己使用的是普通的SS,luci来自
https://github.com/shadowsocks/luci-app-shadowsocks
没有冲突,~~唯一的问题是要排除内网设备的时候,那台设备必须先在KP里完全排除(不过滤).~~**可通过调整防火墙规则顺序解决(确保KP规则在代理规则之上.)**
另外这个repo是基于
https://github.com/openwrt-develop/luci-app-koolproxy
这个改的,iptables的部分没有修改过,是否可以自己排查下?我也不太懂防火墙规则.

**Comment by binge8** [comment]
我说的原版KP就是https://github.com/openwrt-develop/luci-app-koolproxy这个。那个冲突的ssrplus是这个https://github.com/coolsnowwolf/lede/tree/master/package/lean/luci-app-ssr-plus。希望能解决这个冲突。

**Comment by Baozisoftware** [comment]
建议找你用那个ssrplus作者反馈,或者自行修正下防火墙规则顺序.
